site_name: yes-chef
theme: readthedocs

plugins:
  - search
  - mkdocstrings
  - mike

nav:
  - Home: index.md
  - How-to:
      - how-to/walkthrough.md

  - Commands:
      - commands/init.md
      - commands/new_recipe.md
      - commands/export.md
      - commands/new_plan.md
      - commands/plan_recipe.md
      - commands/view_plan.md
      - commands/view_list.md

  - Recipe format:
      - recipe/yaml.md
      - recipe/markdown.md
  - API reference:
      - reference/unit.md
      - reference/shopping_list.md
      - reference/ingredient.md

watch:
  - docs
  - src
