site_name: yes-chef
theme: readthedocs

plugins:
  - search
  - mkdocstrings
  - mike

nav:
  - Home: index.md
  - Commands:
      - commands/recipe_wizard.md
      - commands/export.md
      - commands/new_plan.md
      - commands/plan_recipe.md
      - commands/view_plan.md
      - commands/view_list.md

  - Recipe format:
      - recipe/yaml.md
      - recipe/markdown.md
  - API reference:
      - reference/unit.md
      - reference/shopping_list.md
      - reference/ingredient.md

watch:
  - docs
  - src
