site_name: yes-chef
theme: material

plugins:
  - search
  - mkdocstrings
  - mike

nav:
  - Home: index.md
  - Commands: commands.md
  - Ingredient syntax: ingredient.md
  - API reference:
    - reference/unit.md
    - reference/shopping_list.md
    - reference/ingredient.md

watch:
  - docs
  - src
