name: main-pr

on:
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    name: ruff lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install ruff
      - run: ruff format . --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pytest -p no:cacheprovider --cov --cov-fail-under=80 --cov-report term-missing:skip-covered
